<?php if($adminController -> is_admin() == true): ?>
<div class="addArticle">
	<?php if(isset($message)) : ?>
   		<p class="message"> <?= $message ?> </p>
   	<?php endif; ?>
   	
	<!-- CREATING A USER -->
	<form action="index.php?action=addArtist" method="POST" enctype="multipart/form-data">
		<input type="hidden" name="id_artist">
		<h2>Ajouté un Tatoueur / Tatoueuse</h2>
		<fieldset>
				<div>
				    <!-- Pseudo -->
					<label class="addCenter" for="pseudo">Pseudo</label>
					<input type="text" name="pseudo" id="pseudo" required>
				</div>
				
					<!-- INFO ARTIST -->
				<div>
					<label for="description" class="addCenter">Description</label>
					<textarea class="addCenter contentArea" id="description" name="description"></textarea>
	            </div>
	            
	            <div>
				    <!-- instagram -->
					<label class="addCenter" for="instagram">Instagram</label>
					<input type="text" name="instagram" id="instagram">
				</div>
				
				<!-- PHOTO-->
				<div>
					<input type="file" id="photo" name="photo" accept="photo/png, photo/jpeg">
				</div>
			<button type="submit">Send</button>
			<button type="reset">Cancel</button>
		</fieldset>
		
	</form>
</div>	
<?php else: ?>
<?php header('Location:index.php'); ?>
<?php endif; ?>