<?php if($adminController -> is_admin() == true): ?>
<div class="addArticle">
	<form action="index.php?action=editArtist&id_artist=<?=$artist["id_artist"]?>" method="POST" enctype="multipart/form-data" >
		<h2>Ajouté un Tatoueur / Tatoueuse</h2>
		<fieldset>
				<div>
				    <!-- Pseudo -->
					<label for="pseudo">Pseudo</label>
					<input type="text" name="pseudo" id="pseudo" value="<?= $artist['pseudo'] ?>" required>
				</div>
				
					<!-- INFO ARTIST -->
				<div>
					<label for="description" class="addCenter">Description</label>
					<textarea class="addCenter contentArea" id="description" name="description"><?= $artist['description']?></textarea>
	            </div>
	            
	            <div>
				    <!-- instagram -->
					<label class="addCenter" for="instagram">Instagram</label>
					<input type="text" name="instagram" id="instagram" value="<?=$artist["instagram"]?>">
				</div>
				
				<!-- PHOTO-->
				<div>
					<input type="file" id="photo" name="photo" accept="photo/png, photo/jpeg">
					<img src="www/images/artist/<?= $artist['photo'] ?>" alt="<?= $artist['photo'] ?>">
				</div>
			<button type="submit">Send</button>
			<button type="reset">Cancel</button>
		</fieldset>
		
	</form>
</div>

<?php else: ?>
	<?php header('Location:index.php'); ?>
<?php endif; ?>