


<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- CSS -->
      <link rel="stylesheet" href="www/css/style.css" type="text/css">
      <link rel="stylesheet" href="www/css/normalize.css" type="text/css">
      <!-- FONT AWESOME -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <!-- GOOGLE FONT -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@200;300;400&display=swap" rel="stylesheet"> 
      
      <!-- AJAX -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      
      <!-- FAVICON -->
      <link rel="icon" type="image/png" href="www/images/favicon/favicon-32x32.png">
      
      <title>Mothership Tattoo</title>
   </head>
   <body>
      <header class="header">
         <div class="wrapper">
            <nav class="hamburger">
               <div class="toggle">
                  <button id="btnBurger"><i class="fas fa-bars"></i></button>
               </div>
               <ul>
                  <li><a title="Home" href="index.php">Home</a></li>
                  <li><a title="Contact" href="index.php#cu">Contact</a></li>
                  <li><a title="About us" href="index.php#qsn">About us</a></li>
                  <li><a title="Gallery" href="index.php?action=showTattoo">Gallery</a></li>
                  <?php if($adminController->
                     is_admin()): ?>
                  <li><a title="AdminDashboard" href="index.php?action=connectAdmin">Admin Dashboard</a></li>
                  <li><a title="Disconnection" href="index.php?action=disconnect">Déconnexion</a></li>
                  <?php endif;?>
               </ul>
            </nav>
         
            <div class="linksPC">
               	<div class="headerLinks left">
                  <div class="linky"><a title="Home" href="index.php">Home</a></div>
                  <div class="linky"><a title="Contact" href="index.php#cu">Contact</a></div>
              	</div>
                  <div id="logoWrapper">
                     <a title="HOMElogo" href="index.php"><img src="www/images/content/MTC.png" alt="Mothership Logo"></a>
                  </div>
                <div class="headerLinks right">
                  <div class="linky"><a title="About us" href="index.php#qsn">About us</a></div>
                  <div class="linky"><a title="Gallery" href="index.php?action=showTattoo">Gallery</a></div>
               </div>
               <?php if($adminController->is_admin()): ?>
                     <div class="linkAdmin">
                        <div><a title="Disconnection" href="index.php?action=disconnect">Déconnexion</a></div>
                        <div><a title="AdminDash" href="index.php?action=connectAdmin">Admin Dashboard</a></div>
                     </div>
               <?php endif; ?>
            </div>
         </div>
      </header>
      <main class="container">
         <section>
            <article>
               <?php require $template.".phtml"; ?>
            </article>
         </section>
      </main>
      <footer class="footer">
         <div>
            <a title="instagram" href="https://www.instagram.com/mothership_tattoo_club/"><i class="fab fa-instagram"></i></a>
            <a title="facebook" href="https://www.facebook.com/Mothership-Tattoo-Club-105654307886092"><i class="fab fa-facebook-square"></i></a>
            <a title="email" href="mailto:mothershiptattooclub@gmail.com"><i class="far fa-envelope"></i></a>
         </div>
         

      </footer>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <script src="www/js/slider.js"></script>
      <script src="www/js/mixitup.min.js"></script>
      <script src="www/js/burger.js"></script>
      <!-- Own JS last otherwise, functions added in it wont work as they're loaded after -->
      <script src="www/js/script.js"></script>
   </body>
</html>

