<?php if($adminController -> is_admin() == true): ?>
<div class="addArticle">
	<?php if(isset($message)) : ?>
   		<p class="message"> <?php echo $message ?> </p>
   	<?php endif; ?>

	<form action="index.php?action=addArticle" method="POST" enctype="multipart/form-data" >
		<h2>Ajouter un article</h2>
		<fieldset>
				<div>
				<!-- Article Title -->
					<label for="title" class="addCenter">Title</label>
					<input type="text" name="title" id="title" required class="addCenter">
				</div>
				<div>
				<!-- Article Content -->	
					<label for="content" class="addCenter">Content</label>
					<textarea class="addCenter contentArea" id="content" name="content"></textarea>
	            </div>
				
				<!-- Article Photo -->
				<div>
					<input class="addCenter" type="file" id="photo" name="photo" accept="photo/png, photo/jpeg">
				</div>
				
				<button type="submit">Send</button>
				<button type="reset">Cancel</button>
		</fieldset>
	</form>
<?php else: ?>
	<?php header('Location:index.php'); ?>
<?php endif; ?>