<?php if($adminController -> is_admin() == true): ?>

<?php if(isset($_GET['id_article'])): ?>
<div class="addArticle">
	<form action="index.php?action=editArticle&id_article=<?=$article["id_article"]?>" method="POST" enctype="multipart/form-data" >
		<h2>Éditer un article</h2>
		<fieldset>
				<div>
				<!-- Article Title -->
					<label for="title" class="addCenter">Title</label>
					<input type="text" name="title" id="title" required class="addCenter" value="<?= $article['title'] ?>">
				</div>
				<div>
				<!-- Article Content -->	
					<label for="content" class="addCenter">Content</label>
					<textarea class="addCenter contentArea" id="content" name="content"><?= $article['content'] ?></textarea>
	            </div>
				
				<!-- Article Photo -->
				<div>
					<input class="addCenter" type="file" id="photo" name="photo" accept="photo/png, photo/jpeg" >
					<img src="www/images/articles/<?= $article['photo'] ?>" alt="<?= $article['photo'] ?>">
				</div>
				
				<button type="submit">Send</button>
				<button type="reset">Cancel</button>
		</fieldset>
	</form>
</div>

	<?php else: ?>
<div class="addArticle">
	<?php if(array_key_exists("message",$_GET)) : ?>
        <p class="message"><?= $_GET["message"] ?></p>
    <?php endif; ?>

	
		<table class="tables">
			<thead>
				<tr>
					<th>Article</th>
					<th>Éditer</th>
					<th>Supprimer</th>
			</tr>
			</thead>
			<tbody>
				<?php foreach($articles as $info):?>
				<tr>
					<td><?= $info['title']; ?></td>
					<td><a title="edit" href="index.php?action=editArticle&id_article=<?=$info["id_article"]?>"><i class="fas fa-edit"></a></td>
					<td><a title ="delete" href="index.php?action=removeArticle&id_article=<?=$info["id_article"]?>"><i class="far fa-trash-alt"></i></a></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
</div>
	<?php endif; ?>		
<?php else: ?>
	<?php header('Location:index.php'); ?>
<?php endif; ?>